# Generated by Django 4.0.4 on 2022-04-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='release_date',
            new_name='ti',
        ),
    ]
